# Generated by Django 3.1.7 on 2021-03-26 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gea', '0008_auto_20210324_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='personas',
            field=models.ManyToManyField(blank=True, through='gea.ExpedientePersona', to='gea.Persona'),
        ),
    ]
