# Generated by Django 3.1.7 on 2021-04-02 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gea', '0011_auto_20210331_0332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expediente',
            name='fecha_plano',
        ),
    ]
