# Generated by Django 3.1.7 on 2021-04-04 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gea', '0014_auto_20210402_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='fecha_medicion',
            field=models.DateField(blank=True, null=True, verbose_name='Medición'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='inscripcion_fecha',
            field=models.DateField(blank=True, null=True, verbose_name='SCIT fecha'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='inscripcion_numero',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='SCIT Nº'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='orden_fecha',
            field=models.DateField(blank=True, null=True, verbose_name='CoPA fecha'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='orden_numero',
            field=models.IntegerField(blank=True, null=True, verbose_name='CoPA Nº'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='sin_inscripcion',
            field=models.BooleanField(default=False, verbose_name='No se registra'),
        ),
    ]
