# Generated by Django 3.1.7 on 2021-04-07 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gea', '0015_auto_20210404_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partida',
            name='api',
        ),
        migrations.AlterField(
            model_name='partida',
            name='pii',
            field=models.IntegerField(verbose_name='partida'),
        ),
        migrations.AlterField(
            model_name='partida',
            name='subpii',
            field=models.IntegerField(default=0, verbose_name='subpartida'),
        ),
    ]
