# Generated by Django 3.1.7 on 2021-04-07 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gea', '0016_auto_20210407_0023'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='expedientepartida',
            unique_together={('expediente', 'partida')},
        ),
    ]
