# Generated by Django 3.1.7 on 2021-04-26 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gea', '0017_auto_20210407_0224'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='partida',
            unique_together={('sd', 'pii', 'subpii')},
        ),
    ]
