# Generated by Django 4.1.2 on 2022-11-06 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gea", "0019_auto_20210503_1215"),
    ]

    operations = [
        migrations.AlterField(
            model_name="objeto",
            name="nombre",
            field=models.CharField(max_length=100),
        ),
    ]
