# Generated by Django 5.1.3 on 2025-07-24 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gea", "0020_alter_objeto_nombre"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ds",
            name="ds",
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name="expedientepersona",
            name="nuda_propiedad",
            field=models.BooleanField(default=False, verbose_name="nuda prop"),
        ),
        migrations.AlterField(
            model_name="expedientepersona",
            name="usufructo",
            field=models.BooleanField(default=False, verbose_name="usuf"),
        ),
        migrations.AlterField(
            model_name="partida",
            name="pii",
            field=models.IntegerField(db_index=True, verbose_name="partida"),
        ),
        migrations.AlterField(
            model_name="sd",
            name="sd",
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterUniqueTogether(
            name="ds",
            unique_together={("dp", "ds")},
        ),
        migrations.AlterUniqueTogether(
            name="sd",
            unique_together={("ds", "sd")},
        ),
        migrations.AddIndex(
            model_name="ds",
            index=models.Index(fields=["dp", "ds"], name="idx_ds_dp_ds"),
        ),
        migrations.AddIndex(
            model_name="partida",
            index=models.Index(fields=["pii", "subpii"], name="idx_partida_pii_subpii"),
        ),
        migrations.AddIndex(
            model_name="partida",
            index=models.Index(fields=["sd", "pii"], name="idx_partida_sd_pii"),
        ),
        migrations.AddIndex(
            model_name="sd",
            index=models.Index(fields=["ds", "sd"], name="idx_sd_ds_sd"),
        ),
    ]
