# Generated by Django 5.2.14 on 2026-05-20 04:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gea', '0022_partida_identificador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ds',
            name='ds',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='partida',
            name='pii',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(999999)], verbose_name='partida'),
        ),
        migrations.AlterField(
            model_name='partida',
            name='subpii',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='subpartida'),
        ),
        migrations.AlterField(
            model_name='sd',
            name='sd',
            field=models.IntegerField(),
        ),
        migrations.AddIndex(
            model_name='dp',
            index=models.Index(fields=['nombre'], name='idx_dp_nombre'),
        ),
        migrations.AddIndex(
            model_name='ds',
            index=models.Index(fields=['nombre'], name='idx_ds_nombre'),
        ),
    ]
